name: build 

on: 
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:

  build-debug-ubuntu16:
    name: Debug Build (Ubuntu 16.04)
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - name: install-eigen
        run: sudo apt-get install libeigen3-dev
      - name: configure
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DEigen3_DIR=/usr/lib/cmake/eigen3/ ..
      - name: build
        run: cmake --build build

  build-debug:
    name: Debug Build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install-eigen
      run: sudo apt install libeigen3-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: build
      run: cmake --build build

  build-release:
    name: Release Build
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: install-eigen
      run: sudo apt install libeigen3-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest all

