name: build
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build-debug:
    name: CMake Debug Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install-dependencies
      run: sudo apt install libeigen3-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
    - name: build
      run: cmake --build build
  build-release:
    name: CMake Release Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install-dependencies
      run: sudo apt install libeigen3-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest all
  python:
    name: Python Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup-python
      uses: actions/setup-python@v5
      with: {python-version: '3.x'}
    - name: install-dependencies
      run: sudo apt install libeigen3-dev
    - name: upgrade-pip
      run: python -m pip install --upgrade pip
    - name: build
      run: python -m pip install ${{github.workspace}}
    - name: test
      run: python -c "import teaserpp_python; print('☺')"
